spring.application.name=elearning

# ── CONNEXION MARIADB ─────────────────────────────
spring.datasource.url=jdbc:mariadb://localhost:3306/elearning_odc
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# ── JPA / HIBERNATE ───────────────────────────────
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
spring.jpa.properties.hibernate.format_sql=true

# ── PORT DU SERVEUR ───────────────────────────────
server.port=8080

# ── NOM DE L'APPLICATION ──────────────────────────
spring.application.name=elearning

# ── UPLOAD DE FICHIERS ────────────────────────────
# Chemin absolu : les fichiers restent accessibles quel que soit
# le dossier depuis lequel le backend est lancé (VS Code, Maven...)
app.upload.dir=C:/Users/Diallo/Desktop/SiteE_learning/backend/uploads
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=210MB

# ── JWT ───────────────────────────────────────────
jwt.secret=odc_elearning_secret_key_2026_guinee
jwt.expiration=86400000